### ISSUE TITLE
function isPhoneNumber regex

### ISSUE THREAD

**Issue by ngmisl** [lakeraai/chrome-extension#1]
Tried the extension, but it seems to have very weak phone number recognition, here's some recommendation (by GPT4)

`const phoneRegex = /((\+|00)(\d{1,3}))?[-.\s]?(\()?(\d{1,4})(?(4)\))[-.\s]?(\d{1,4})[-.\s]?(\d{4,7})/g;`

This regex pattern will detect phone numbers in the following formats:

- +1 (123) 456-7890
- +1-123-456-7890
- +1.123.456.7890
- +1 123 456 7890
- 123-456-7890
- 123.456.7890
- 123 456 7890
- (123) 456-7890
- 00123 456 7890
- 00123-456-7890
- 00123.456.7890
- 00(123) 456-7890

**Comment by santiaago** [comment]
Thanks for the issue, we'll see if we can handle this in the coming month.
